### ISSUE TITLE
Connecting the latest Mifos Mobile to ezbank 

### ISSUE THREAD

**Issue by francisguchie** [francisguchie/mifos-mobile#17]
Connect the latest Mifos mobile to ezbank

**Comment by francisguchie** [comment]
@rrpawar96  
should we update ezbank to allow for json body at login ?
like in https://issues.apache.org/jira/browse/FINERACT-726 and https://github.com/apache/fineract/pull/678 

please advise

**Comment by rrpawar96** [comment]
@francisguchie , yes we will update ezbank(fineract) to latest to allow authentication with json body.
